Point(U)
Point(V)
Point(W)
Point(X)
Point(Y)
Triangle(U,V,X)
Triangle(V,W,Y)
Collinear(Point(U), Point(V), Point(W))
PointLiesOnLine(Point(X), Line(U,W))
PointLiesOnLine(Point(Y), Line(U,W))
Congruent(Line(W,Y), Line(V,X))
Congruent(Line(V,Y), Line(U,X))
IsMidpointOf(Point(V), Line(U,W))
Prove(Congruent(Triangle(V,W,Y), Triangle(U,V,X)))