Point(T)
Point(W)
Point(R)
Point(V)
Point(S)
Point(U)
Triangle(T,W,R)
Triangle(V,S,R)
IntersectAt(Line(T,W), Line(V,S), Point(U))
IntersectAt(Line(V,S), Line(R,T), Point(S))
IntersectAt(Line(T,W), Line(V,R), Point(W))
CongruentAngle(Angle(V,R,S), Angle(T,R,W))
Congruent(Line(S,V), Line(T,W))
Prove(Congruent(Triangle(R,T,W), Triangle(R,V,S)))