Point(T)
Point(U)
Point(S)
Point(V)
Point(W)
Triangle(T,W,U)
Triangle(S,V,W)
Line(T,U)
Line(S,V)
Congruent(Line(T,U), Line(S,V))
Parallel(Line(T,U), Line(S,V))
Prove(Congruent(Triangle(S,V,W), Triangle(U,T,W)))