Point(S)
Point(R)
Point(P)
Point(Q)
Triangle(S,R,P)
Triangle(Q,R,P)
Line(P,R)
BisectsAngle(Line(P,R), Angle(Q,R,S))
BisectsAngle(Line(P,R), Angle(Q,P,S))
Prove(Congruent(Triangle(P,R,S), Triangle(P,R,Q)))