Point(W)
Point(Y)
Point(S)
Point(Z)
Point(X)
Point(T)
Point(V)
Point(U)
Line(W,Y)
Line(S,Z)
Line(T,V)
IntersectAt(Line(W,Y), Line(S,Z), Point(X))
IntersectAt(Line(T,V), Line(S,Z), Point(U))
Supplementary(Angle(U,X,W), Angle(T,U,X))
Prove(Parallel(Line(W,Y), Line(T,V)))