Point(V)
Point(X)
Point(R)
Point(Y)
Point(W)
Point(S)
Point(U)
Point(T)
Line(V,X)
Line(R,Y)
Line(S,U)
IntersectAt(Line(V,X), Line(R,Y), Point(W))
IntersectAt(Line(S,U), Line(R,Y), Point(T))
Collinear(Point(Y), Point(W), Point(T), Point(R))
Supplementary(Angle(S,T,W), Angle(T,W,V))
Prove(Parallel(Line(V,X), Line(S,U)))