Point(P)
Point(R)
Point(S)
Point(Q)
Point(T)
Triangle(P,R,S)
Line(Q,T)
Line(P,S)
Line(P,R)
IntersectAt(Line(Q,T), Line(P,S), Point(T))
IntersectAt(Line(Q,T), Line(P,R), Point(Q))
CongruentAngle(Angle(P,T,Q), Angle(P,Q,T))
Parallel(Line(Q,T), Line(R,S))
Prove(CongruentAngle(Angle(S,R,Q), Angle(Q,R,S)))