Point(T)
Point(U)
Point(W)
Point(S)
Point(V)
Triangle(T,U,W)
Triangle(S,V,W)
Angle(S)
Angle(T,U,W)
Line(S,V)
Line(T,U)
CongruentAngle(Angle(S), Angle(U,T,W))
Parallel(Line(S,V), Line(T,U))
Prove(CongruentAngle(Angle(T,U,W), Angle(V)))