Point(T)
Point(U)
Point(W)
Point(S)
Point(V)
Triangle(T,U,W)
Triangle(S,V,W)
CongruentAngle(Angle(S,V,W), Angle(U,T,W))
Parallel(Line(S,V), Line(T,U))
Prove(CongruentAngle(Angle(T,U,W), Angle(V,S,W)))