Point(F)
Point(H)
Point(V)
Point(X)
Point(S)
Point(U)
Point(R)
Point(Y)
Point(G)
Point(W)
Point(T)
Line(F,H)
Line(V,X)
Line(S,U)
Line(R,Y)
IntersectAt(Line(F,H), Line(R,Y), Point(G))
IntersectAt(Line(V,X), Line(R,Y), Point(W))
IntersectAt(Line(S,U), Line(R,Y), Point(T))
Collinear(Point(Y), Point(G), Point(W), Point(T), Point(R))
Ordered(Point(Y), Point(G), Point(W), Point(T), Point(R))
Parallel(Line(F,H), Line(V,X))
Parallel(Line(S,U), Line(F,H))
Prove(Supplementary(Angle(R,T,U), Angle(X,W,Y)))