Point(F)
Point(H)
Point(V)
Point(X)
Point(S)
Point(U)
Point(R)
Point(Y)
Point(G)
Point(W)
Point(T)
Line(F,H)
Line(V,X)
Line(S,U)
Line(R,Y)
IntersectAt(Line(F,H), Line(R,Y), Point(G))
IntersectAt(Line(V,X), Line(R,Y), Point(W))
IntersectAt(Line(S,U), Line(R,Y), Point(T))
Collinear(R, Y, G)
Collinear(R, Y, W)
Collinear(R, Y, T)
Parallel(Line(F,H), Line(V,X))
Parallel(Line(S,U), Line(F,H))
Prove(Equals(SumOf(MeasureOf(Angle(R,T,U)), MeasureOf(Angle(X,W,Y))), 180))