Point(A)
Point(B)
Point(C)
Triangle(A,B,C)
Point(A1)
Point(B1)
Point(C1)
Triangle(A1,B1,C1)
Equals(SideOf(Triangle(A1,B1,C1)), Add(SideOf(Triangle(A,B,C)), HalfOf(SideOf(Triangle(B,C,A)))))
Equals(SideOf(Triangle(B1,C1,A1)), Add(SideOf(Triangle(B,C,A)), HalfOf(SideOf(Triangle(C,A,B)))))
Equals(SideOf(Triangle(C1,A1,B1)), Add(SideOf(Triangle(C,A,B)), HalfOf(SideOf(Triangle(A,B,C)))))
Prove(GreaterThanOrEqual(AreaOf(Triangle(A1,B1,C1)), Mul(Div(9,4), AreaOf(Triangle(A,B,C)))))