Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Triangle(A,B,C)
Isosceles(Triangle(A,B,C))
Circle(Γ)
PointLiesOnCircle(Point(D), Circle(Γ))
PointLiesOnCircle(Point(E), Circle(Γ))
Arc(A,B)
Arc(A,C)
Equals(LengthOf(Line(A,B)), LengthOf(Line(A,C)))
Equals(LengthOf(Line(A,D)), LengthOf(Line(C,E)))
Prove(Parallel(Line(B,E), Line(A,D)))