Point(A)
Point(B)
Point(C)
Point(D)
Triangle(A,B,C)
PointLiesOnLine(Point(D), Line(B,C))
Equals(Add(LengthOf(Line(A,B)), LengthOf(Line(B,D))), Add(LengthOf(Line(A,C)), LengthOf(Line(C,D))))
IsCentroidOf(Point(G1), Triangle(A,B,D))
IsCentroidOf(Point(G2), Triangle(A,C,D))
PointLiesOnCircle(Point(B), Circle(O))
PointLiesOnCircle(Point(C), Circle(O))
PointLiesOnCircle(Point(G1), Circle(O))
PointLiesOnCircle(Point(G2), Circle(O))
Prove(Equals(LengthOf(Line(A,B)), LengthOf(Line(A,C))))