Point(A)
Point(B)
Point(C)
Point(D)
Triangle(A,B,C)
PointLiesOnLine(Point(D), Line(B,C))
BisectsAngle(Line(A,D), Angle(B,A,C))
Equals(Angle(B), Mul(2, Angle(C)))
Equals(LengthOf(Line(C,D)), LengthOf(Line(A,B)))
Prove(Equals(Angle(A,B,C), 72))