Point(A)
Point(B)
Point(C)
Triangle(A,B,C)
Circumradius(R, Triangle(A,B,C))
SideOf(Line(B,C), Triangle(A,B,C))
SideOf(Line(C,A), Triangle(A,B,C))
SideOf(Line(A,B), Triangle(A,B,C))
Exradius(ra, Triangle(A,B,C), Point(A))
Exradius(rb, Triangle(A,B,C), Point(B))
Exradius(rc, Triangle(A,B,C), Point(C))
LessThanOrEqual(Mul(2, R), ra)
Prove(GreaterThan(SideOf(Line(B,C), Triangle(A,B,C)), SideOf(Line(C,A), Triangle(A,B,C))))
Prove(GreaterThan(SideOf(Line(B,C), Triangle(A,B,C)), SideOf(Line(A,B), Triangle(A,B,C))))
Prove(GreaterThan(Mul(2, R), rb))
Prove(GreaterThan(Mul(2, R), rc))