Point(A)
Point(B)
Point(C)
Point(P)
Point(Q)
Triangle(A,B,C)
Circle(Γ)
Diameter(Line(B,C), Circle(Γ))
IntersectAt(Circle(Γ), Line(A,B), Point(P))
IntersectAt(Circle(Γ), Line(A,C), Point(Q))
Orthocenter(Point(H), Triangle(A,P,Q))
PointLiesOnCircle(Point(H), Circle(Γ))
Find(MeasureOf(Angle(B,A,C)))