Point(O)
Point(O')
Point(A)
Point(M)
Point(B)
Circle(O)
Circle(O')
PointLiesOnCircle(Point(O'), Circle(O))
PointLiesOnCircle(Point(A), Circle(O'))
PointLiesOnCircle(Point(B), Circle(O'))
IsMidpointOf(Point(M), Line(A,O'))
Parallel(Line(A,B), Line(O,M))
Prove(PointLiesOnCircle(Midpoint(Point(A), Point(B)), Circle(O)))