Point(A)
Point(B)
Point(C)
Point(E)
Point(F)
Point(M)
Triangle(A,B,C)
Angle(A,B,C)
Bisector(Angle(B,A,C))
Bisector(Angle(C,A,B))
PointLiesOnLine(Point(E), Line(A,C))
PointLiesOnLine(Point(F), Line(A,B))
Reflect(Point(M), Line(E,F))
Equals(MeasureOf(Angle(A,B,C)), 60)
Prove(PointLiesOnLine(Point(M), Line(B,C)))