Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Point(P)
Point(Q)
Point(R)
Point(S)
Triangle(A,B,C)
RightAngle(Angle(A,B,C))
IsAltitudeOf(Line(B,D), Triangle(A,B,C))
Perpendicular(Line(D,E), Line(A,B))
Perpendicular(Line(D,F), Line(B,C))
IsIncenterOf(Point(P), Triangle(D,F,C))
IsIncenterOf(Point(Q), Triangle(D,B,F))
IsIncenterOf(Point(R), Triangle(D,E,B))
IsIncenterOf(Point(S), Triangle(D,A,E))
Collinear(Point(S), Point(R), Point(Q))
Prove(CircumscribedTo(Circle(D), Shape(P,Q,R,D)))