Point(A)
Point(B)
Point(C)
Point(D)
Point(H)
Point(K)
Triangle(A,B,C)
IsAltitudeOf(Line(A,D), Triangle(A,B,C))
IsOrthocenterOf(Point(H), Triangle(A,B,C))
Circle(K)
PointLiesOnCircle(Point(D), Circle(K))
Tangent(Line(B,H), Circle(K))
Prove(BisectsAngle(Line(D,K), Angle(A,C,K)))