Point(A)
Point(B)
Point(C)
Point(M)
Point(N)
Triangle(A,B,C)
Isosceles(Triangle(A,B,C))
RightAngle(Angle(C,A,B))
PointLiesOnLine(Point(M), Line(B,C))
PointLiesOnLine(Point(N), Line(B,C))
Equals(LengthOf(Line(A,B)), LengthOf(Line(A,C)))
Equals(Add(Pow(LengthOf(Line(B,M)), 2), Pow(LengthOf(Line(C,N)), 2)), Pow(LengthOf(Line(M,N)), 2))
Prove(Equals(MeasureOf(Angle(M,A,N)), 45))