Point(A)
Point(B)
Point(C)
Point(X)
Point(Y)
Triangle(A,B,C)
AcuteAngle(Angle(A,B,C))
PerpendicularBisector(Line(B,C))
PerpendicularBisector(Line(B,A))
IntersectAt(PerpendicularBisector(Line(B,C)), Line(A,C), Point(X))
IntersectAt(PerpendicularBisector(Line(B,A)), Line(A,C), Point(Y))
IsCircumcenterOf(Point(O), Triangle(A,B,C))
IsIncenterOf(Point(O), Triangle(B,X,Y))
Prove(IsCircumcenterOf(Point(O), Triangle(A,B,C)), IsIncenterOf(Point(O), Triangle(B,X,Y)))