Point(A)
Point(B)
Point(C)
Point(D)
Point(P)
Point(E)
Point(F)
Point(G)
Point(H)
Quadrilateral(A,B,C,D)
Line(A,C)
Line(B,D)
IntersectAt(Line(A,C), Line(B,D), Point(P))
IsAltitudeOf(Line(P,E), Triangle(A,B,P))
IsAltitudeOf(Line(P,F), Triangle(B,C,P))
IsAltitudeOf(Line(P,G), Triangle(C,D,P))
IsAltitudeOf(Line(P,H), Triangle(D,A,P))
Prove(Equals(Add(Div(1, LengthOf(Line(P,E))), Div(1, LengthOf(Line(P,G)))), Add(Div(1, LengthOf(Line(P,F))), Div(1, LengthOf(Line(P,H))))))
Prove(InscribedIn(Circle($), Quadrilateral(A,B,C,D)))