Point(A)
Point(B)
Point(C)
Point(K)
Point(L)
Point(M)
Point(P)
Point(Q)
Triangle(A,B,C)
Circle(O)
PointLiesOnCircle(Point(K), Circle(O))
PointLiesOnCircle(Point(L), Circle(O))
PointLiesOnCircle(Point(M), Circle(O))
PointLiesOnLine(Point(K), Line(B,C))
PointLiesOnLine(Point(L), Line(C,A))
PointLiesOnLine(Point(M), Line(A,B))
Line(L,K)
Line(M,K)
ParallelThrough(Line(L,K), Point(A))
ParallelThrough(Line(M,K), Point(A))
IntersectAt(Line(A,LK), Line(M,K), Point(P))
IntersectAt(Line(A,MK), Line(L,K), Point(Q))
Prove(IsMidpointOf(Point(P), Line(A,B)))
Prove(IsMidpointOf(Point(Q), Line(A,C)))