Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Point(A')
Point(D')
Point(G)
Square(A,B,C,D)
Line(E,F)
Line(A',D')
IntersectAt(Line(A',D'), Line(C,D), Point(G))
PointLiesOnLine(Point(B), Line(B,C))
Triangle(G,C,A')
Triangle(G,D',F)
Triangle(A',B,E)
Prove(Equals(SumOf(InradiusOf(Triangle(G,D',F)), InradiusOf(Triangle(A',B,E))), InradiusOf(Triangle(G,C,A'))))