Point(A)
Point(B)
Point(C)
Point(M)
Point(A1)
Point(B1)
Point(C1)
Point(P)
Point(Q)
Triangle(A,B,C)
Circle(Gamma)
PointLiesOnCircle(Point(A), Circle(Gamma))
PointLiesOnCircle(Point(B), Circle(Gamma))
PointLiesOnCircle(Point(C), Circle(Gamma))
Inside(Point(M), Triangle(A,B,C))
BisectsAngle(Line(A,M), Angle(B,A,C))
IntersectAt(Line(A,M), Circle(Gamma), Point(A1))
IntersectAt(Line(B,M), Circle(Gamma), Point(B1))
IntersectAt(Line(C,M), Circle(Gamma), Point(C1))
IntersectAt(Line(A1,C1), Line(A,B), Point(P))
IntersectAt(Line(A1,B1), Line(A,C), Point(Q))
Prove(Parallel(Line(P,Q), Line(B,C)))