Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Quadrilateral(A,B,C,D)
Triangle(D,A,C)
Circle(O)
PointLiesOnCircle(Point(E), Circle(O))
Angle(A,B,D)
Angle(B,C,A)
Angle(A,C,D)
Equals(MeasureOf(Angle(A,B,D)), 30)
Equals(MeasureOf(Angle(B,C,A)), 75)
Equals(MeasureOf(Angle(A,C,D)), 25)
Congruent(Line(C,D), Line(C,B))
Prove(Congruent(Line(C,E), Line(B,D)))