Point(A)
Point(B)
Point(C)
Point(P)
Point(M)
Point(N)
Triangle(A,B,C)
IsMidpointOf(Point(M), Line(A,C))
IsMidpointOf(Point(N), Line(B,C))
RightAngle(Angle(B,P,C))
CongruentAngle(Angle(B,A,P), Angle(B,C,P))
Equals(LengthOf(Line(B,P)), Mul(2, LengthOf(Line(P,M))))
Prove(Collinear(Point(A), Point(P), Point(N)))