Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Point(I1)
Point(I2)
Point(I3)
Triangle(A,B,C)
Triangle(A,F,E)
Triangle(B,D,F)
Triangle(C,E,D)
Incircle(Triangle(A,B,C))
PointLiesOnLine(Point(D), Line(B,C))
PointLiesOnLine(Point(E), Line(C,A))
PointLiesOnLine(Point(F), Line(A,B))
IsIncenterOf(Point(I1), Triangle(A,F,E))
IsIncenterOf(Point(I2), Triangle(B,D,F))
IsIncenterOf(Point(I3), Triangle(C,E,D))
Concurrent(Line(I1,D), Line(I2,E), Line(I3,F), $)