Point(A)
Point(B)
Point(C)
Point(E)
Point(F)
Point(X)
Point(Y)
Triangle(A,B,C)
Line(B,E)
Line(C,F)
Segment(C,F)
Segment(B,E)
PointLiesOnLine(Point(E), Line(A,C))
PointLiesOnLine(Point(F), Line(A,B))
BisectsAngle(Line(B,E), Angle(C,B,A))
BisectsAngle(Line(C,F), Angle(B,C,A))
PointLiesOnLine(Point(X), Segment(C,F))
PointLiesOnLine(Point(Y), Segment(B,E))
Perpendicular(Line(A,X), Line(C,F))
Perpendicular(Line(A,Y), Line(B,E))
Prove(Equals(LengthOf(Line(X,Y)), Div(Add(Add(b,c), Sub(a)), 2)))