Point(A)
Point(B)
Point(C)
Point(D)
Point(O)
Point(E)
Triangle(A,B,C)
Circle(O)
PointLiesOnCircle(Point(D), Circle(O))
BisectsAngle(Line(A,D), Angle(B,A,C))
IntersectAt(Line(D,O), Line(A,C), Point(E))
Perpendicular(Line(B,E), Line(A,D))
Prove(Parallel(Line(A,O), Line(B,D)))