Point(A)
Point(B)
Point(C)
Point(I)
Triangle(A,B,C)
Isosceles(Triangle(A,B,C))
Equals(LengthOf(Line(A,B)), LengthOf(Line(A,C)))
IsIncenterOf(Point(I), Triangle(A,B,C))
Equals(LengthOf(Line(B,C)), Add(LengthOf(Line(A,B)), LengthOf(Line(A,I))))
Find(MeasureOf(Angle(B,A,C)))