Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Point(G)
Point(H)
Circle(Γ)
Quadrilateral(A,B,C,D)
Arc(A,B)
Arc(B,C)
Arc(C,D)
Arc(D,A)
IsMidpointOf(Point(E), Arc(A,B))
IsMidpointOf(Point(F), Arc(B,C))
IsMidpointOf(Point(G), Arc(C,D))
IsMidpointOf(Point(H), Arc(D,A))
Equals(Mul(LengthOf(Line(A,C)), LengthOf(Line(B,D))), Mul(LengthOf(Line(E,G)), LengthOf(Line(F,H))))
Prove(Concurrent(Line(A,C), Line(B,D), Line(E,G), Line(F,H)))