Point(A)
Point(B)
Point(C)
Point(O)
Point(P)
Point(Q)
Red(Point(O))
Blue(Point(P))
Green(Point(Q))
RightAngle(Angle(A,B,C))
Prove(Exists(Triangle(A,B,C), IsRight(Triangle(A,B,C)), Red(Point(A)), Blue(Point(B)), Green(Point(C))))