Point(A)
Point(B)
Point(C)
Point(I)
Point(F)
Point(E)
Triangle(A,B,C)
RightAngle(Angle(A,B,C))
IsIncenterOf(Point(I), Triangle(A,B,C))
Line(A,I)
IntersectAt(Line(A,I), Line(B,C), Point(F))
PerpendicularThrough(Line(A,I), Point(I))
IntersectAt(Line(I,E), Line(A,C), Point(E))
Prove(Congruent(Line(I,E), Line(I,F)))