Point(A)
Point(B)
Point(C)
Point(R)
Point(X)
Triangle(A,B,C)
AcuteAngle(Angle(A,B,C))
IsCircumcenterOf(Point(R), Triangle(A,B,C))
Circle(R)
PointLiesOnCircle(Point(X), Circle(R))
IntersectAt(Circle(R), Line(A,C), Point(X))
Prove(Perpendicular(Line(R,X), Line(B,C)))