Point(O1)
Point(O2)
Point(R)
Point(P)
Point(Q)
Point(K)
Circle(O1)
Circle(O2)
Line(l1)
Line(l2)
Tangent(Line(l1), Circle(O2))
Tangent(Line(l2), Circle(O2))
PointLiesOnCircle(Point(R), Circle(O1))
PointLiesOnCircle(Point(R), Circle(O2))
Touches(Circle(O1), Circle(O2))
PointLiesOnLine(Point(P), Line(l1))
PointLiesOnLine(Point(Q), Line(l2))
IntersectAt(Line(l1), Line(l2), Point(K))
Equals(DistanceBetween(Point(K), Point(P)), DistanceBetween(Point(K), Point(Q)))
Prove(Equilateral(Triangle(P,Q,R)))