Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Triangle(A,B,C)
PointLiesOnLine(Point(D), Line(B,C))
PointLiesOnLine(Point(E), Line(C,A))
PointLiesOnLine(Point(F), Line(A,B))
Equals(LengthOf(Line(B,D)), LengthOf(Line(C,E)))
Equals(LengthOf(Line(C,E)), LengthOf(Line(A,F)))
CongruentAngle(Angle(B,D,F), Angle(C,E,D))
CongruentAngle(Angle(C,E,D), Angle(A,F,E))
Prove(Equilateral(Triangle(A,B,C)))