Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Hexagon(A,B,C,D,E,F)
Parallel(Line(A,B), Line(D,E))
Equals(LengthOf(Line(A,E)), LengthOf(Line(B,D)))
Parallel(Line(B,C), Line(E,F))
Equals(LengthOf(Line(B,F)), LengthOf(Line(C,E)))
Parallel(Line(C,D), Line(F,A))
Equals(LengthOf(Line(C,A)), LengthOf(Line(D,F)))
Prove(CircumscribedTo(Hexagon(A,B,C,D,E,F), Circle($)))