Point(A)
Point(B)
Point(C)
Point(D)
Point(P)
Point(Q)
Point(R)
Point(S)
Quadrilateral(A,B,C,D)
IsMidpointOf(Point(P), Line(A,B))
IsMidpointOf(Point(Q), Line(B,C))
IsMidpointOf(Point(R), Line(C,D))
IsMidpointOf(Point(S), Line(D,A))
Equilateral(Triangle(A,Q,R))
Equilateral(Triangle(C,S,P))
Prove(Rhombus(A,B,C,D))
Find(Angle(A,B,C))
Find(Angle(B,C,D))
Find(Angle(C,D,A))
Find(Angle(D,A,B))