Point(A)
Point(B)
Point(C)
Point(O)
Point(I)
Circle(ΓA)
Circle(ΓB)
Circle(ΓC)
Circle(Γ)
Triangle(A,B,C)
Inside(Circle(ΓA), Triangle(A,B,C))
Inside(Circle(ΓB), Triangle(A,B,C))
Inside(Circle(ΓC), Triangle(A,B,C))
Touches(Circle(ΓA), Line(A,B))
Touches(Circle(ΓA), Line(A,C))
Touches(Circle(ΓB), Line(A,B))
Touches(Circle(ΓB), Line(B,C))
Touches(Circle(ΓC), Line(B,C))
Touches(Circle(ΓC), Line(C,A))
Touches(Circle(Γ), Circle(ΓA))
Touches(Circle(Γ), Circle(ΓB))
Touches(Circle(Γ), Circle(ΓC))
IsCircumcenterOf(Point(O), Triangle(A,B,C))
IsIncenterOf(Point(I), Triangle(A,B,C))
Prove(PointLiesOnLine(Point(CenterOf(Circle(Γ))), Line(O,I)))