Point(A)
Point(B)
Point(C)
Point(H)
Triangle(A,B,C)
IsOrthocenterOf(Point(H), Triangle(A,B,C))
IsAltitudeOf(Line(A,H), Triangle(A,B,C))
IsAltitudeOf(Line(B,H), Triangle(A,B,C))
IsAltitudeOf(Line(C,H), Triangle(A,B,C))
Prove(LessThanOrEqual(SumOf(LengthOf(Line(A,H)), LengthOf(Line(B,H)), LengthOf(Line(C,H))), Mul(2, h_max)))