Point(A)
Point(B)
Point(C)
Point(P)
Point(M)
Point(Q)
Triangle(A,B,C)
Line(A,B)
Line(B,C)
Line(A,M)
PointLiesOnLine(Point(P), Line(A,B))
PointLiesOnLine(Point(Q), Line(A,B))
IsMidpointOf(Point(M), Line(B,C))
Equals(Add(LengthOf(Line(A,P)), LengthOf(Line(P,C))), LengthOf(Line(A,B)))
Perpendicular(Line(C,Q), Line(A,M))
Prove(Equals(LengthOf(Line(B,Q)), Mul(2, LengthOf(Line(A,P)))))