Point(A)
Point(B)
Point(C)
Point(D)
Point(P)
Point(Q)
Point(I)
Triangle(A,B,C)
Triangle(A,B,D)
Triangle(C,B,D)
RightAngle(Angle(A,B,C))
IsAltitudeOf(Line(B,D), Triangle(A,B,C))
IsIncenterOf(Point(P), Triangle(A,B,D))
IsIncenterOf(Point(Q), Triangle(C,B,D))
IsIncenterOf(Point(I), Triangle(A,B,C))
Prove(OnBoundary(Point(Circumcenter(Triangle(P,I,Q))), Line(A,C)))