Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(P)
Triangle(A,B,C)
PointLiesOnLine(Point(D), Line(B,C))
Equals(LengthOf(Line(D,C)), Mul(2, LengthOf(Line(B,D))))
IsMidpointOf(Point(E), Line(A,C))
IntersectAt(Line(A,D), Line(B,E), Point(P))
Find(RatioOf(LengthOf(Line(B,P)), LengthOf(Line(P,E))))
Find(RatioOf(LengthOf(Line(A,P)), LengthOf(Line(P,D))))