Point(O1)
Point(O2)
Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Circle(O1)
Circle(O2)
Circle(O1,A,O2)
Triangle(O1,A,O2)
PointLiesOnCircle(Point(A), Circle(O1))
PointLiesOnCircle(Point(A), Circle(O2))
PointLiesOnCircle(Point(B), Circle(O1))
PointLiesOnCircle(Point(B), Circle(O2))
IntersectAt(Circle(O1), Circle(O2), Point(A))
IntersectAt(Circle(O1), Circle(O2), Point(B))
ObtuseAngle(Angle(O1,A,O2))
PointLiesOnCircle(Point(C), Circle(O1,A,O2))
PointLiesOnCircle(Point(D), Circle(O1,A,O2))
IntersectAt(Line(C,B), Circle(O2), Point(E))
IntersectAt(Line(D,B), Circle(O1), Point(F))
Prove(Cyclic(Quadrilateral(C,D,E,F)))