Point(A)
Point(B)
Point(C)
Point(D)
Point(K)
Point(L)
Point(M)
Point(N)
Point(Q)
Quadrilateral(A,B,C,D)
IsMidpointOf(Point(K), Line(A,B))
IsMidpointOf(Point(L), Line(B,C))
IsMidpointOf(Point(M), Line(C,D))
IsMidpointOf(Point(N), Line(D,A))
BisectsAngle(Line(B,D), Line(K,M))
Equals(DistanceBetween(Point(Q), Point(A)), DistanceBetween(Point(Q), Point(B)))
Equals(DistanceBetween(Point(Q), Point(B)), DistanceBetween(Point(Q), Point(C)))
Equals(DistanceBetween(Point(Q), Point(C)), DistanceBetween(Point(Q), Point(D)))
Equals(RatioOf(LengthOf(Line(L,K)), LengthOf(Line(L,M))), RatioOf(LengthOf(Line(C,D)), LengthOf(Line(C,B))))
Prove(Square(A,B,C,D))