Point(A)
Point(B)
Point(C)
Point(P)
Point(A1)
Point(B1)
Point(C1)
Triangle(A,B,C)
Triangle(A1,B1,C1)
Reflect(Point(P), Line(B,C), Point(A1))
Reflect(Point(P), Line(C,A), Point(B1))
Reflect(Point(P), Line(A,B), Point(C1))
Prove(Implies(Or(IsIncenterOf(Point(P), Triangle(A,B,C)), IsExcenterOf(Point(P), Triangle(A,B,C))), IsCircumcenterOf(Point(P), Triangle(A1,B1,C1))))
Prove(Implies(IsCircumcenterOf(Point(P), Triangle(A,B,C)), IsOrthocenterOf(Point(P), Triangle(A1,B1,C1))))
Prove(Implies(IsOrthocenterOf(Point(P), Triangle(A,B,C)), Or(IsIncenterOf(Point(P), Triangle(A1,B1,C1)), IsExcenterOf(Point(P), Triangle(A1,B1,C1)))))