Point(A)
Point(B)
Point(C)
Point(E)
Point(F)
Point(Q)
Triangle(A,B,C)
Segment(B,C)
Segment(A,C)
IsMidpointOf(Point(F), Line(A,C))
IntersectAt(Line(B,F), Line(A,E), Point(Q))
Equals(RatioOf(DistanceBetween(Point(B), Point(E)), DistanceBetween(Point(E), Point(C))), 2)
Find(RatioOf(DistanceBetween(Point(B), Point(Q)), DistanceBetween(Point(Q), Point(F))))