Point(A)
Point(B)
Point(C)
Point(M)
Point(K)
Point(L)
Triangle(A,B,C)
IsMidpointOf(Point(M), Line(B,C))
MedianOf(Line(A,M), Triangle(A,B,C))
Incircle(Circle(I), Triangle(A,B,C))
IntersectAt(Line(A,M), Circle(I), Point(K))
IntersectAt(Line(A,M), Circle(I), Point(L))
Between(Point(K), Point(L), Point(M))
Equals(LengthOf(Line(A,K)), LengthOf(Line(K,L)))
Equals(LengthOf(Line(K,L)), LengthOf(Line(L,M)))
Prove(RatioOf(SideOf(Triangle(A,B,C)), SideOf(Triangle(A,B,C)), SideOf(Triangle(A,B,C))) = (5, 10, 13))