Point(A)
Point(B)
Point(C)
Triangle(A,B,C)
Not(IsRight(Triangle(A,B,C)))
Sequence(Triangle(Ai,Bi,Ci), i, GreaterThanOrEqual(i, 0))
Equals(Triangle(A0,B0,C0), Triangle(A,B,C))
ForAll(i, GreaterThanOrEqual(i, 0), Reflection(Orthocenter(Triangle(Ai,Bi,Ci)), Line(Bi,Ci), Point(Ai+1)))
ForAll(i, GreaterThanOrEqual(i, 0), Reflection(Orthocenter(Triangle(Ai,Bi,Ci)), Line(Ci,Ai), Point(Bi+1)))
ForAll(i, GreaterThanOrEqual(i, 0), Reflection(Orthocenter(Triangle(Ai,Bi,Ci)), Line(Ai,Bi), Point(Ci+1)))
Equals(Angle(Am), Angle(An))
Prove(Equals(Angle(A,B,C), 60))