Point(A1)
Point(A2)
Point(A3)
Point(P)
Circle(Gamma)
PointLiesOnCircle(Point(A1), Circle(Gamma))
PointLiesOnCircle(Point(A2), Circle(Gamma))
PointLiesOnCircle(Point(A3), Circle(Gamma))
Triangle(A1,A2,A3)
Point(P1)
Point(P2)
Point(P3)
Prove(LessThanOrEqual(RadiusOf(Circle(P1,P2,P3)), RadiusOf(Circle(Gamma))))