Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Point(P)
Point(Q)
Triangle(A,B,C)
Segment(B,C)
PointLiesOnLine(Point(D), Segment(B,C))
PointLiesOnLine(Point(E), Segment(B,C))
Equals(LengthOf(Line(B,D)), LengthOf(Line(D,E)))
Equals(LengthOf(Line(D,E)), LengthOf(Line(E,C)))
IsMidpointOf(Point(F), Line(A,C))
IntersectAt(Line(B,F), Line(A,D), Point(P))
IntersectAt(Line(B,F), Line(A,E), Point(Q))
Calculate(Div(LengthOf(Line(B,P)), LengthOf(Line(P,Q))))