Point(O1)
Point(O2)
Point(A)
Point(B)
Point(C)
Point(D)
Point(X)
Point(Y)
Point(P)
Point(Q)
Circle(O1)
Circle(O2)
Tangent(Line(B,C), Circle(O1))
Tangent(Line(B,D), Circle(O2))
IntersectAt(Line(B,C), Circle(O2), Point(C))
IntersectAt(Line(B,D), Circle(O1), Point(D))
Bisector(Angle(D,A,B))
Bisector(Angle(C,A,B))
PointLiesOnCircle(Point(X), Circle(O1))
PointLiesOnCircle(Point(Y), Circle(O2))
IsCircumcenterOf(Point(P), Triangle(A,C,D))
IsCircumcenterOf(Point(Q), Triangle(X,A,Y))
Prove(IsPerpendicularBisectorOf(Line(P,Q), Line(O1,O2)))