Point(A)
Point(B)
Point(C)
Point(H)
Point(P)
Point(Q)
Point(R)
Triangle(A,B,C)
IsOrthocenterOf(Point(H), Triangle(A,B,C))
Line(B,C)
Reflection(Point(P), Point(A), Line(B,C))
Circle(O1)
Circle(O2)
Circumcircle(Triangle(A,B,P))
Circumcircle(Triangle(A,C,P))
IntersectAt(Circle(O1), Line(B,H), Point(Q))
IntersectAt(Circle(O2), Line(C,H), Point(R))
Prove(IsIncenterOf(Point(H), Triangle(P,Q,R)))