Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Point(I)
Triangle(A,B,C)
Triangle(A,B,D)
Triangle(A,C,D)
IsIncenterOf(Point(I), Triangle(A,B,C))
PointLiesOnLine(Point(D), Line(B,C))
PointLiesOnLine(Point(E), Line(A,B))
PointLiesOnLine(Point(F), Line(B,C))
Prove(Cyclic(Polygon(B,E,I,F)))