Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Triangle(A,B,C)
PointLiesOnLine(Point(D), Line(B,C))
PointLiesOnLine(Point(E), Line(C,A))
PointLiesOnLine(Point(F), Line(A,B))
Equals(Div(LengthOf(Line(C,D)), LengthOf(Line(C,E))), Div(LengthOf(Line(C,A)), LengthOf(Line(C,B))))
Equals(Div(LengthOf(Line(A,E)), LengthOf(Line(A,F))), Div(LengthOf(Line(A,B)), LengthOf(Line(A,C))))
Equals(Div(LengthOf(Line(B,F)), LengthOf(Line(B,D))), Div(LengthOf(Line(B,C)), LengthOf(Line(B,A))))
Prove(IsAltitudeOf(Line(A,D), Triangle(A,B,C)))
Prove(IsAltitudeOf(Line(B,E), Triangle(A,B,C)))
Prove(IsAltitudeOf(Line(C,F), Triangle(A,B,C)))