Point(A)
Point(B)
Point(C)
Point(D)
Point(O1)
Point(O2)
Triangle(A,B,C)
Triangle(A,B,D)
Triangle(A,C,D)
Segment(B,C)
PointLiesOnLine(Point(D), Segment(B,C))
IsCircumcenterOf(Point(O1), Triangle(A,B,D))
IsCircumcenterOf(Point(O2), Triangle(A,C,D))
IsCircumcenterOf(Point(O), Triangle(A,B,C))
IsOrthocenterOf(Point(H), Triangle(O1,O2,D))
Line(O,H)
Line(B,C)
Prove(Parallel(Line(O,H), Line(B,C)))