Point(A)
Point(B)
Point(C)
Point(D)
Point(X)
Point(Y)
Point(O)
Point(P)
Point(Q)
Point(R)
Point(S)
Quadrilateral(A,B,C,D)
IsMidpointOf(Point(X), Line(A,C))
IsMidpointOf(Point(Y), Line(B,D))
ParallelThrough(Line(B,D), Point(X))
ParallelThrough(Line(A,C), Point(Y))
IntersectAt(Line(X,Y), Line(O,O), Point(O))
IsMidpointOf(Point(P), Line(A,B))
IsMidpointOf(Point(Q), Line(B,C))
IsMidpointOf(Point(R), Line(C,D))
IsMidpointOf(Point(S), Line(D,A))
Prove(Equals(AreaOf(Quadrilateral(A,P,O,S)), AreaOf(Quadrilateral(A,P,X,S))))
Prove(Equals(AreaOf(Quadrilateral(A,P,O,S)), AreaOf(Quadrilateral(B,Q,O,P))))
Prove(Equals(AreaOf(Quadrilateral(A,P,O,S)), AreaOf(Quadrilateral(C,R,O,Q))))
Prove(Equals(AreaOf(Quadrilateral(A,P,O,S)), AreaOf(Quadrilateral(D,S,O,R))))