Point(A)
Point(B)
Point(C)
Point(I)
Point(A')
Point(B')
Point(C')
Point(P)
Point(Q)
Point(R)
Triangle(A,B,C)
Circle(Γ)
IsIncenterOf(Point(I), Triangle(A,B,C))
Angle(A,B,C)
Angle(B,C,A)
Angle(C,A,B)
BisectsAngle(Line(A,A'), Angle(B,A,C))
BisectsAngle(Line(B,B'), Angle(A,B,C))
BisectsAngle(Line(C,C'), Angle(A,C,B))
PointLiesOnCircle(Point(A'), Circle(Γ))
PointLiesOnCircle(Point(B'), Circle(Γ))
PointLiesOnCircle(Point(C'), Circle(Γ))
IntersectAt(Line(B',C'), Line(A,A'), Point(P))
IntersectAt(Line(B',C'), Line(A,C), Point(Q))
IntersectAt(Line(B,B'), Line(A,C), Point(R))
Kite(Quadrilateral(P,I,R,Q))
Equals(DistanceBetween(Point(I), Point(P)), DistanceBetween(Point(I), Point(R)))
Equals(DistanceBetween(Point(Q), Point(P)), DistanceBetween(Point(Q), Point(R)))
Prove(Equilateral(Triangle(A,B,C)))