Point(A)
Point(B)
Point(C)
Point(D)
Triangle(A,B,C)
IsMidpointOf(Point(D), Line(B,C))
Angle(A,D,B)
Angle(A,C,D)
Equals(MeasureOf(Angle(A,D,B)), 45)
Equals(MeasureOf(Angle(A,C,D)), 30)
Find(MeasureOf(Angle(B,A,D)))