Point(A)
Point(B)
Point(C)
Point(D)
Circle(O)
Quadrilateral(A,B,C,D)
PointLiesOnCircle(Point(A), Circle(O))
PointLiesOnCircle(Point(B), Circle(O))
PointLiesOnCircle(Point(C), Circle(O))
PointLiesOnCircle(Point(D), Circle(O))
Equals(LengthOf(Line(A,B)), Add(SqrtOf(2), SqrtOf(2)))
Angle(A,O,B)
Equals(MeasureOf(Angle(A,O,B)), 135)
Find(Maximum(AreaOf(Quadrilateral(A,B,C,D))))