Point(A)
Point(B)
Point(C)
Point(I)
Point(A1)
Point(B1)
Point(C1)
Point(I1)
Triangle(A,B,C)
Triangle(A1,B1,C1)
IsIncenterOf(Point(I), Triangle(A,B,C))
Reflect(Point(I), Line(B,C), Point(A1))
Reflect(Point(I), Line(C,A), Point(B1))
Reflect(Point(I), Line(A,B), Point(C1))
PointLiesOnCircle(Point(A), Circle(Circumcircle(Triangle(A1,B1,C1))))
IsIncenterOf(Point(I1), Triangle(A1,B1,C1))
Prove(Concyclic(Point(B1), Point(C1), Point(I), Point(I1)))