Point(A)
Point(B)
Point(C)
Point(D)
Point(P)
Point(Q)
Point(I)
Triangle(A,B,C)
RightAngle(Angle(B,A,C))
LessThan(LengthOf(Line(A,B)), LengthOf(Line(A,C)))
IsAltitudeOf(Line(A,D), Triangle(A,B,C))
IsIncenterOf(Point(P), Triangle(A,B,D))
IsIncenterOf(Point(Q), Triangle(A,C,D))
IsIncenterOf(Point(I), Triangle(A,B,C))
Perpendicular(Line(A,I), Line(P,Q))
Prove(Equals(LengthOf(Line(A,I)), LengthOf(Line(P,Q)))