Point(A)
Point(B)
Point(C)
Point(E)
Point(F)
Point(G)
Circle(O)
Triangle(A,B,C)
Triangle(E,G,B)
Triangle(E,C,F)
PointLiesOnCircle(Point(E), Circle(O))
Equals(LengthOf(Line(C,A)), LengthOf(Line(C,B)))
RightAngle(Angle(E,C,B))
ParallelThrough(Line(E,G), Line(C,B))
IntersectAt(Line(E,G), Line(C,A), Point(F))
IntersectAt(Line(E,G), Line(A,B), Point(G))
Prove(PointLiesOnCircle(Point(O), Circle(E,C,F)))