Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Point(K)
Point(P)
Triangle(A,B,C)
PointLiesOnLine(Point(E), Line(A,C))
PointLiesOnLine(Point(F), Line(A,B))
IntersectAt(Line(A,P), Line(E,F), Point(D))
Perpendicular(Line(D,K), Line(B,C))
BisectsAngle(Line(D,K), Angle(E,K,F))
Prove(BisectsAngle(Line(D,K), Angle(E,K,F)))