Point(A)
Point(B)
Point(C)
Point(G)
Point(X)
Point(Y)
Triangle(A,B,C)
IsCentroidOf(Point(G), Triangle(A,B,C))
Circle(O1)
Circle(O2)
Triangle(A,G,B)
Triangle(A,G,C)
CircumscribedTo(Circle(O1), Triangle(A,G,B))
CircumscribedTo(Circle(O2), Triangle(A,G,C))
IntersectAt(Circle(O1), Line(B,C), Point(X))
IntersectAt(Circle(O2), Line(B,C), Point(Y))
Prove(IsCentroidOf(Point(G), Triangle(A,X,Y)))