Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Triangle(A,B,C)
RightAngle(Angle(B,A,C))
Equals(LengthOf(Line(A,B)), LengthOf(Line(A,C)))
PointLiesOnLine(Point(D), Line(B,C))
PointLiesOnLine(Point(E), Line(B,C))
RatioOf(DistanceBetween(Point(B), Point(D)), DistanceBetween(Point(D), Point(E)), DistanceBetween(Point(E), Point(C))) = (3, 5, 4)
Prove(Equals(MeasureOf(Angle(D,A,E)), 45))