Point(A)
Point(B)
Point(C)
Point(P)
Point(Q)
Point(R)
Line(A,C)
Between(Point(A), Point(B), Point(C))
Triangle(P,A,B)
Triangle(Q,B,C)
Triangle(R,A,C)
Isosceles(Triangle(P,A,B))
Isosceles(Triangle(Q,B,C))
Isosceles(Triangle(R,A,C))
Angle(A,P,B)
Angle(B,Q,C)
Angle(A,R,C)
Equals(MeasureOf(Angle(A,P,B)), 120)
Equals(MeasureOf(Angle(B,Q,C)), 120)
Equals(MeasureOf(Angle(A,R,C)), 120)
Prove(Equilateral(Triangle(P,Q,R)))