Point(A)
Point(B)
Point(C)
Point(D)
Point(O)
Triangle(A,B,C)
Triangle(A,D,C)
IsMidpointOf(Point(D), Line(B,C))
CongruentAngle(Angle(D,A,B), Angle(B,C,A))
Equals(MeasureOf(Angle(D,A,C)), 15)
IsCircumcenterOf(Point(O), Triangle(A,D,C))
Prove(ObtuseAngle(Angle(L,A,D)))
Prove(Equilateral(Triangle(A,O,D)))