Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Triangle(A,B,C)
Segment(B,C)
PointLiesOnLine(Point(D), Line(B,C))
Line(A,D)
PointLiesOnLine(Point(E), Line(A,D))
Circle(O)
Tangent(Line(A,B), Circle(O))
CircumscribedTo(Circle(O), Triangle(A,C,D))
Perpendicular(Line(B,E), Line(A,D))
Equals(LengthOf(Line(C,A)), LengthOf(Line(C,D)))
Equals(LengthOf(Line(A,E)), LengthOf(Line(C,E)))
GreaterThan(MeasureOf(Angle(B,A,C)), 90)
Find(MeasureOf(Angle(B,C,A)))