Point(A)
Point(B)
Point(C)
Point(D)
Quadrilateral(A,B,C,D)
Parallel(Line(A,B), Line(C,D))
Perpendicular(Line(A,B), Line(A,D))
Equals(Mul(3, LengthOf(Line(C,D))), LengthOf(Line(A,B)))
CircumscribedTo(Circle(O,r), Quadrilateral(A,B,C,D))
Equals(AreaOf(Quadrilateral(A,B,C,D)), 4)
Find(RadiusOf(Circle(O,r)))