Point(A1)
Point(B1)
Point(C1)
Point(D1)
Point(E1)
Pentagon(A1,B1,C1,D1,E1)
Regular(Polygon(A1,B1,C1,D1,E1))
Point(An)
Point(Bn)
Point(Cn)
Point(Dn)
Point(En)
Pentagon(An,Bn,Cn,Dn,En)
Midpoint(Point(An), Line(A(n-1),B(n-1)))
Midpoint(Point(Bn), Line(B(n-1),C(n-1)))
Midpoint(Point(Cn), Line(C(n-1),D(n-1)))
Midpoint(Point(Dn), Line(D(n-1),E(n-1)))
Midpoint(Point(En), Line(E(n-1),A(n-1)))
Prove(Exists(Points(P1,P2,P3,P4),
SameColor(Point(P1), Point(P2), Point(P3), Point(P4)),
CyclicQuadrilateral(Point(P1), Point(P2), Point(P3), Point(P4))