Point(A)
Point(B)
Point(C)
Triangle(A,B,C)
Red(Point(A))
Red(Point(B))
Red(Point(C))
Isosceles(Triangle(A,B,C))
Prove(Exists(Triangle(A,B,C), Or(Isosceles(Triangle(A,B,C)), GeometricProgression(Angle(A,B,C), Angle(B,C,A), Angle(C,A,B)))))