Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Point(K)
Triangle(A,B,C)
RightAngle(Angle(A,B,C))
Bisector(Angle(B,A,C))
PointLiesOnLine(Point(D), Line(B,C))
PointLiesOnCircle(Point(E), Circle(A,C,D))
PointLiesOnLine(Point(E), Line(A,B))
PointLiesOnCircle(Point(F), Circle(A,B,D))
PointLiesOnLine(Point(F), Line(A,C))
Reflection(Point(K), Point(E), Line(B,C))
Prove(Equals(LengthOf(Line(F,K)), LengthOf(Line(B,C))))