Point(A)
Point(B)
Point(C)
Point(D)
Point(O)
Point(M)
Trapezoid(A,B,C,D)
Circle(O)
Line(A,B)
Line(C,D)
Line(A,C)
Line(B,D)
IntersectAt(Line(A,C), Line(B,D), Point(M))
Parallel(Line(A,B), Line(C,D))
InscribedIn(Trapezoid(A,B,C,D), Circle(O))
Equals(DistanceBetween(Point(O), Point(M)), 2)
Angle(A,M,B)
Angle(A,M,D)
Prove(Difference(LengthOf(Line(A,B)), LengthOf(Line(C,D))))