Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(P)
Point(S)
Triangle(A,B,C)
PointLiesOnLine(Point(D), Line(B,C))
PointLiesOnLine(Point(E), Line(A,C))
Equals(RatioOf(LengthOf(Line(B,D)), LengthOf(Line(D,C))), 3)
Equals(RatioOf(LengthOf(Line(A,E)), LengthOf(Line(E,C))), 4)
PointLiesOnLine(Point(P), Line(E,D))
IsMidpointOf(Point(D), Line(E,P))
IntersectAt(Line(A,P), Line(B,C), Point(S))
Find(RatioOf(LengthOf(Line(B,S)), LengthOf(Line(S,D))))