Point(A)
Point(B)
Point(C)
Point(D)
Point(P)
Point(E)
Triangle(A,B,C)
Isosceles(Triangle(A,B,C))
Equals(LengthOf(Line(A,B)), LengthOf(Line(A,C)))
IsMidpointOf(Point(D), Line(B,C))
PointLiesOnLine(Point(P), Line(A,D))
Perpendicular(Line(P,E), Line(A,C))
Equals(Div(LengthOf(Line(A,P)), LengthOf(Line(P,D))), m)
Equals(Div(LengthOf(Line(B,P)), LengthOf(Line(P,E))), m)
Equals(Div(LengthOf(Line(B,D)), LengthOf(Line(A,D))), m)
Equals(z, Mul(Pow(m,2), Add(1, lambda)))
Prove(Equals(Pow(z,2), Add(Sub(Pow(lambda,3), Pow(lambda,2)), Sub(-2, z), 1)))
Prove(GreaterThanOrEqual(lambda, 2))
Prove(Equals(lambda, 2) <=> Equilateral(Triangle(A,B,C)))