Point(A)
Point(B)
Point(C)
Point(D)
Circle(Γ)
Triangle(A,B,C)
Triangle(A,B,D)
Line(A,B)
Line(A,C)
Line(B,C)
Line(B,D)
PointLiesOnLine(Point(D), Line(A,C))
PointLiesOnCircle(Point(B), Circle(Γ))
PointLiesOnCircle(Point(C), Circle(Γ))
PointLiesOnCircle(Point(D), Circle(Γ))
Tangent(Line(A,B), Circle(Γ))
IsOrthocenterOf(Point(H), Triangle(A,B,D))
Prove(IntersectAt(Line(H), PerpendicularBisector(Line(B,C)), Point(H)))