Point(A)
Point(B)
Point(C)
Point(D)
Quadrilateral(A,B,C,D)
Circle(O)
PointLiesOnCircle(Point(A), Circle(O))
PointLiesOnCircle(Point(B), Circle(O))
PointLiesOnCircle(Point(C), Circle(O))
PointLiesOnCircle(Point(D), Circle(O))
Equals(LengthOf(Line(A,B)), a)
Equals(LengthOf(Line(B,C)), b)
Equals(LengthOf(Line(C,D)), c)
AngleBetween(Line(A,B), Line(B,C), 120)
AngleBetween(Line(A,B), Line(B,D), 30)
Prove(GreaterThanOrEqual(c, Add(a, b)))
Prove(Equals(Abs(Sub(SqrtOf(Add(c, a)), SqrtOf(Add(c, b)))), SqrtOf(Sub(c, Add(a, b)))))