Point(P)
Point(Q)
Point(R)
Point(S)
Quadrilateral(P,Q,R,S)
Equals(LengthOf(Line(P,Q)), LengthOf(Line(R,S)))
Equals(Mul(Add(SqrtOf(3), 1), LengthOf(Line(Q,R))), LengthOf(Line(S,P)))
Equals(Sub(MeasureOf(Angle(R,S,P)), MeasureOf(Angle(S,P,Q))), 30)
Prove(Equals(Sub(MeasureOf(Angle(P,Q,R)), MeasureOf(Angle(Q,R,S))), 90))