Point(O)
Point(A)
Point(B)
Point(C)
Point(D)
Point(P)
Circle(O)
Circle(O,$)
Diameter(C,D)
IntersectAt(Line(C,D), Circle(O,$), Point(P))
IntersectAt(Circle(O), Circle(O,$), Point(A))
IntersectAt(Circle(O), Circle(O,$), Point(B))
Prove(CongruentAngle(Angle(A,P,C), Angle(B,P,D)))