Point(A)
Point(B)
Point(C)
Point(D)
Circle(Gamma)
Circle(Sigma)
PointLiesOnCircle(Point(A), Circle(Gamma))
PointLiesOnCircle(Point(A), Circle(Sigma))
PointLiesOnCircle(Point(B), Circle(Gamma))
PointLiesOnCircle(Point(B), Circle(Sigma))
Line(B,C)
Line(B,D)
IntersectAt(Line(B,C), Circle(Gamma), Point(C))
IntersectAt(Line(B,D), Circle(Sigma), Point(D))
Equals(DistanceBetween(Point(C), Point(A)), DistanceBetween(Point(C), Point(D)))
Prove(PointLiesOnCircle(Point(CenterOf(Circle(Sigma))), Circle(Gamma)))