Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Circle(Gamma)
Circle(Sigma)
PointLiesOnCircle(Point(A), Circle(Gamma))
PointLiesOnCircle(Point(A), Circle(Sigma))
PointLiesOnCircle(Point(B), Circle(Gamma))
PointLiesOnCircle(Point(B), Circle(Sigma))
PointLiesOnCircle(Point(C), Circle(Gamma))
PointLiesOnCircle(Point(D), Circle(Sigma))
PointLiesOnCircle(Point(E), Circle(Sigma))
Collinear(Point(C), Point(B), Point(D))
Parallel(Line(D,E), Line(A,C))
Prove(Equals(LengthOf(Line(A,E)), LengthOf(Line(A,B))))