Point(A)
Point(B)
Point(C)
Point(X)
Point(D)
Triangle(A,B,C)
Segment(B,C)
PointLiesOnLine(Point(X), Segment(B,C))
Equals(LengthOf(Line(A,B)), LengthOf(Line(A,X)))
Circle(Γ)
PointLiesOnCircle(Point(A), Circle(Γ))
PointLiesOnCircle(Point(B), Circle(Γ))
PointLiesOnCircle(Point(X), Circle(Γ))
IntersectAt(Line(A,X), Circle(Γ), Point(D))
Prove(PointLiesOnCircle(Point(O), Circle(Γ)))