Point(A)
Point(B)
Point(C)
Point(D)
Point(K)
Circle(Gamma)
Line(A,B)
Line(C,D)
Triangle(A,D,K)
IsDiameterOf(Line(A,B), Circle(Gamma))
PointLiesOnCircle(Point(C), Circle(Gamma))
Perpendicular(Line(C,D), Line(A,B))
Between(Point(C), Point(K), Point(D))
Equals(LengthOf(Line(A,C)), HalfOf(SumOf(LengthOf(Line(A,D)), LengthOf(Line(D,K)), LengthOf(Line(K,A)))))
Prove(Tangent(Excircle(Triangle(A,D,K), Point(A)), Circle(Gamma)))