Point(A)
Point(B)
Point(C)
Point(O)
Point(H)
Point(G)
Point(D)
Point(E)
Point(F)
Triangle(A,B,C)
IsCircumcenterOf(Point(O), Triangle(A,B,C))
IsOrthocenterOf(Point(H), Triangle(A,B,C))
IsCentroidOf(Point(G), Triangle(A,B,C))
IsMidpointOf(Point(F), Line(A,B))
PointLiesOnLine(Point(D), Line(B,C))
PointLiesOnLine(Point(E), Line(C,A))
Perpendicular(Line(O,D), Line(B,C))
Perpendicular(Line(H,E), Line(C,A))
Equals(AreaOf(Triangle(O,D,C)), AreaOf(Triangle(H,E,A)))
Equals(AreaOf(Triangle(O,D,C)), AreaOf(Triangle(G,F,B)))
Find(MeasureOf(Angle(A,B,C)))