Point(A)
Point(B)
Point(C)
Point(I)
Point(D)
Triangle(A,B,C)
RightAngle(Angle(A,B,C))
IsIncenterOf(Point(I), Triangle(A,B,C))
Line(A,I)
Line(C,B)
PerpendicularThrough(Line(A,I), Point(I))
IntersectAt(Line(C,B), Line(D,I), Point(D))
Perpendicular(Line(C,I), Line(A,D))
Prove(Equals(LengthOf(Line(I,D)), SqrtOf(Mul(b, Sub(b, a)))))