Point(A)
Point(B)
Point(C)
Point(E)
Point(F)
Point(O)
Point(K)
Point(L)
Point(M)
Point(N)
Triangle(A,B,C)
Line(B,E)
Line(C,F)
Line(K,L)
Line(F,M)
Line(E,N)
IntersectAt(Line(B,E), Line(C,F), Point(O))
PointLiesOnLine(Point(E), Line(A,C))
PointLiesOnLine(Point(F), Line(A,B))
PointLiesOnLine(Point(K), Line(A,B))
PointLiesOnLine(Point(L), Line(A,C))
PointLiesOnLine(Point(M), Line(B,E))
PointLiesOnLine(Point(N), Line(C,F))
Perpendicular(Line(K,M), Line(B,E))
Perpendicular(Line(L,N), Line(C,F))
Prove(Parallel(Line(F,M), Line(E,N)))