Point(A)
Point(B)
Point(C)
Point(B')
Point(C')
Triangle(A,B,C)
Triangle(A,B',C')
Bisector(Angle(B,A,C))
Reflect(Point(B), Bisector(Angle(B,A,C)), Point(B'))
Reflect(Point(C), Bisector(Angle(B,A,C)), Point(C'))
IsIncenterOf(Point(I), Triangle(A,B,C))
IsIncenterOf(Point(I), Triangle(A,B',C'))
Prove(Equals(Point(I), Point(I)))