Point(A)
Point(B)
Point(C)
Point(O)
Point(X)
Point(Y)
Point(D)
Point(E)
Triangle(A,B,C)
IsCircumcenterOf(Point(O), Triangle(A,B,C))
PerpendicularBisector(Line(B,C))
PerpendicularBisector(Line(A,B))
IntersectAt(PerpendicularBisector(Line(B,C)), Line(A,C), Point(X))
IntersectAt(PerpendicularBisector(Line(A,B)), Line(A,C), Point(Y))
BisectsAngle(Line(A,X), Angle(A,X,B))
BisectsAngle(Line(B,Y), Angle(B,Y,C))
PointLiesOnLine(Point(D), Line(A,B))
PointLiesOnLine(Point(E), Line(B,C))
Parallel(Line(D,E), Line(A,C))
Prove(Perpendicular(Line(B,O), Line(A,C)))