Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Pentagon(A,B,C,D,E)
Convex(Polygon(A,B,C,D,E))
Equals(MeasureOf(Angle(A,B,C)), 120)
Equals(MeasureOf(Angle(B,C,D)), 120)
Equals(MeasureOf(Angle(C,D,E)), 120)
Equals(MeasureOf(Angle(D,E,A)), 120)
Equals(MeasureOf(Angle(E,A,B)), 120)
Find(SumOf(LengthOf(Line(A,B)), LengthOf(Line(B,C)), LengthOf(Line(C,D))))