Point(A)
Point(B)
Point(C)
Point(B')
Point(I)
Line(l)
Triangle(A,B,C)
Triangle(C,B',I)
Bisector(Angle(C,A,B))
Reflect(Point(B), Line(l), Point(B'))
IsIncenterOf(Point(I), Triangle(A,B,C))
CircumcenterOf(Triangle(C,B',I))
Prove(PointLiesOnLine(Point(CircumcenterOf(Triangle(C,B',I))), Line(l)))