Point(A)
Point(B)
Point(C)
Point(D)
Point(E)
Point(F)
Triangle(A,B,C)
PointLiesOnLine(Point(D), Line(B,C))
PointLiesOnLine(Point(E), Line(C,A))
PointLiesOnLine(Point(F), Line(A,B))
IsMedianOf(Line(A,D), Triangle(A,B,C))
BisectsAngle(Line(B,E), Angle(C,B,A))
IsAltitudeOf(Line(C,F), Triangle(A,B,C))
CongruentAngle(Angle(F,D,E), Angle(L,C))
CongruentAngle(Angle(D,E,F), Angle(L,A))
CongruentAngle(Angle(E,F,D), Angle(L,B))
Prove(Equilateral(Triangle(A,B,C)))