Point(U)
Point(V)
Point(W)
Point(X)
Triangle(U,V,W)
Line(U,X)
Line(V,W)
IntersectAt(Line(U,X), Line(V,W), Point(X))
PointLiesOnLine(Point(X), Line(V,W))
CongruentAngle(Angle(W,U,X), Angle(V,U,X))
Perpendicular(Line(V,W), Line(U,X))
Prove(Congruent(Line(W,X), Line(V,X)))