Point(R)
Point(S)
Point(T)
Point(U)
Triangle(R,S,T)
Line(R,U)
Line(S,T)
IntersectAt(Line(R,U), Line(S,T), Point(U))
IsMidpointOf(Point(U), Line(S,T))
Congruent(Line(R,T), Line(R,S))
Prove(CongruentAngle(Angle(S), Angle(T)))