Point(R)
Point(P)
Point(Q)
Point(S)
Triangle(R,P,Q)
Line(P,S)
Line(R,Q)
IntersectAt(Line(P,S), Line(R,Q), Point(S))
BisectsAngle(Line(P,S), Angle(Q,P,R))
Congruent(Line(P,Q), Line(P,R))
Prove(Congruent(Line(Q,S), Line(R,S)))