Point(F)
Point(G)
Point(H)
Point(I)
Triangle(F,G,H)
Line(F,I)
Line(G,H)
IntersectAt(Line(F,I), Line(G,H), Point(I))
PointLiesOnLine(Point(I), Line(G,H))
Perpendicular(Line(F,I), Line(G,H))
IsMidpointOf(Point(I), Line(G,H))
Prove(CongruentAngle(Angle(H), Angle(G)))