Point(F)
Point(G)
Point(H)
Point(I)
Triangle(F,G,H)
Line(F,I)
Line(G,H)
IntersectAt(Line(F,I), Line(G,H), Point(I))
Perpendicular(Line(F,I), Line(G,H))
IsMidpointOf(Point(I), Line(G,H))
Prove(CongruentAngle(Angle(F,H,I), Angle(F,G,I)))