Point(S)
Point(T)
Point(W)
Point(R)
Point(U)
Point(V)
Triangle(S,T,W)
Triangle(R,U,V)
CongruentAngle(Angle(S), Angle(R))
Equals(RatioOf(LengthOf(Line(S,W)), LengthOf(Line(R,V))), RatioOf(LengthOf(Line(S,T)), LengthOf(Line(R,U))))
Prove(CongruentAngle(Angle(S,W,T), Angle(R,V,U)))