Point(H)
Point(J)
Point(G)
Point(I)
Point(F)
Triangle(H,J,G)
Triangle(I,F,J)
Equals(RatioOf(LengthOf(Line(G,J)), LengthOf(Line(I,J))), RatioOf(LengthOf(Line(H,J)), LengthOf(Line(F,J))))
Prove(Similar(Triangle(G,H,J), Triangle(I,F,J)))