Point(J)
Point(G)
Point(F)
Point(I)
Point(H)
Triangle(J,G,F)
Triangle(I,H,F)
Line(I,H)
IntersectAt(Line(I,H), Line(J,F), Point(I))
IntersectAt(Line(I,H), Line(F,G), Point(H))
Equals(RatioOf(LengthOf(Line(F,I)), LengthOf(Line(F,J))), RatioOf(LengthOf(Line(F,H)), LengthOf(Line(F,G))))
Prove(Similar(Triangle(F,H,I), Triangle(F,G,J)))