Point(U)
Point(R)
Point(S)
Point(T)
Triangle(U,R,S)
Line(U,T)
Line(R,S)
IntersectAt(Line(U,T), Line(R,S), Point(T))
Perpendicular(Line(R,U), Line(S,U))
Perpendicular(Line(T,U), Line(R,S))
Prove(Similar(Triangle(S,T,U), Triangle(U,T,R)))