Point(V)
Point(W)
Point(Y)
Point(X)
Quadrilateral(V,W,Y,X)
Line(V,X)
Perpendicular(Line(W,X), Line(V,W))
Perpendicular(Line(X,Y), Line(V,Y))
CongruentAngle(Angle(X,V,Y), Angle(V,X,W))
Prove(Congruent(Line(X,Y), Line(V,W)))