Point(U)
Point(V)
Point(T)
Point(S)
Point(W)
Quadrilateral(U,V,T,S)
Line(V,T)
Line(U,S)
IntersectAt(Line(V,T), Line(U,S), Point(W))
Congruent(Line(S,T), Line(T,U))
Congruent(Line(S,V), Line(U,V))
Prove(Congruent(Line(U,W), Line(S,W)))