Point(S)
Point(T)
Point(R)
Point(U)
Point(V)
Quadrilateral(S,T,R,U)
Line(T,R)
Line(U,S)
IntersectAt(Line(T,R), Line(U,S), Point(V))
Parallel(Line(T,U), Line(R,S))
Parallel(Line(R,U), Line(S,T))
Congruent(Line(R,T), Line(S,U))
Prove(Perpendicular(Line(R,S), Line(S,T)))