Point(W)
Point(V)
Point(X)
Point(Y)
Point(Z)
Quadrilateral(W,V,X,Y)
Line(V,X)
Line(W,Y)
Line(X,Y)
Line(V,Z)
Parallel(Line(X,Y), Line(V,W))
Parallel(Line(V,Z), Line(W,Y))
Parallel(Line(Y,Z), Line(V,W))
Congruent(Line(V,X), Line(W,Y))
Prove(Congruent(Line(V,Y), Line(W,X)))